version: '3.9'

services:
  nginx:
    image: nginx:1.15
    container_name: nginx
    volumes:
      - ./:/var/www
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./app/nginx/ODproj.crt:/etc/ssl/certs/ODproj.crt
      - ./app/nginx/ODproj.key:/etc/ssl/private/ODproj.key
    ports:
      - 443:443
      - 80:80
    networks:
      - my-network
    depends_on:
      - flask
  flask:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: flask
    command: gunicorn "main:app"
    volumes:
      - ./:/var/www
    networks:
      my-network:
        aliases:
          - flask-app

networks:
  my-network: